export const ADD_ITEM_REQUEST = 'ADD_ITEM_REQUEST'
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS'

export const REMOVE_ITEM_REQUEST = 'REMOVE_ITEM_REQUEST'
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS'

export const UPDATE_QUANTITY_REQUEST = 'UPDATE_QUANTITY_REQUEST'
export const UPDATE_QUANTITY_SUCCESS = 'UPDATE_QUANTITY_SUCCESS'
export const UPDATE_QUANTITY_FAILURE = 'UPDATE_QUANTITY_FAILURE'

export const INCREASE_QUANTITY_REQUEST = 'INCREASE_QUANTITY_REQUEST'
export const INCREASE_QUANTITY_SUCCESS = 'INCREASE_QUANTITY_SUCCESS'

export const DECREASE_QUANTITY_REQUEST = 'DECREASE_QUANTITY_REQUEST'
export const DECREASE_QUANTITY_SUCCESS = 'DECREASE_QUANTITY_SUCCESS'